<?php
require_once($_SERVER['DOCUMENT_ROOT'] . '/classes/aliApi.php');
require_once($_SERVER['DOCUMENT_ROOT'] . '/classes/log.php');
require_once($_SERVER['DOCUMENT_ROOT'] . '/classes/db.php');
require_once($_SERVER['DOCUMENT_ROOT'] . '/classes/MS/ordersMS.php');
require_once($_SERVER['DOCUMENT_ROOT'] . '/classes/MS/productsMS.php');
require_once($_SERVER['DOCUMENT_ROOT'] . '/config.php');
require_once($_SERVER['DOCUMENT_ROOT'] . '/aliapi/TopSdk.php');

$req = new CainiaoGlobalSolutionInquiryRequest;
$req->setLocale("ru_RU");
$trade_order_param = new OpenTradeOrderParam;
$trade_order_param->trade_order_id="";
$req->setTradeOrderParam(json_encode($trade_order_param));
$seller_info_param = new OpenSellerInfoParam;
$req->setSellerInfoParam(json_encode($seller_info_param));

$c = new TopClient;
$c->appkey = '31422861';
$c->secretKey = '6f2e8e80a97089d9af1a4f3519e73718';
$req = new CainiaoGlobalLogisticOrderCreateRequest;
$order_param = new OpenOrderParam;
$trade_order_param = new OpenTradeOrderParam;
$trade_order_param->trade_order_id="5013374986134593";
$order_param->trade_order_param = $trade_order_param;
$solution_param = new OpenSolutionParam;
$solution_param->solution_code="AE_RU_MP_PUDO_PH3";
$service_params = new OpenServiceParam;
$service_params->code="DOOR_PICKUP";
$features = new Features;
$service_params->features = $features;
$solution_param->service_params = $service_params;
$order_param->solution_param = $solution_param;
$seller_info_param = new OpenSellerInfoParam;
$order_param->seller_info_param = $seller_info_param;
$sender_param = new OpenSenderParam;
$sender_param->seller_address_id="430000082402";
$order_param->sender_param = $sender_param;
$returner_param = new OpenReturnerParam;
$returner_param->seller_address_id="430000082398";
$order_param->returner_param = $returner_param;
$receiver_param = new ReceiverParam;
$order_param->receiver_param = $receiver_param;
$pickup_info_param = new OpenPickupInfoParam;
$pickup_info_param->seller_address_id="430000082402";
$order_param->pickup_info_param = $pickup_info_param;
$package_params = new OpenPackageParam;
$item_params = new OpenItemParam;
$item_params->item_id="1005001513131806";
$item_params->quantity="1";
$item_params->english_name="Lion Laundry Powder Blue Diamond box 900g";
$item_params->local_name="Lion Laundry Powder Blue Diamond box 900g";
$item_params->unit_price="1";
$item_params->sku="{\"sku\":[{\"pName\":\"Ships From\",\"pValueId\":201336103,\"pValue\":\"Russian Federation\",\"pId\":200007763,\"order\":2}]}";
$item_params->weight="1000";
$item_params->currency="RUB";
$item_params->total_price="640";
$package_params->item_params[] = $item_params;
$item_params = new OpenItemParam;
$item_params->item_id="1005001562646484";
$item_params->quantity="1";
$item_params->english_name="Meine Liebe gel wash colored fabrics concentrate луговые flowers 800 ml";
$item_params->local_name="Meine Liebe gel wash colored fabrics concentrate луговые flowers 800 ml";
$item_params->unit_price="1";
$item_params->sku="{\"sku\":[{\"pName\":\"Ships From\",\"pValueId\":201336103,\"pValue\":\"Russian Federation\",\"pId\":200007763,\"order\":2}]}";
$item_params->weight="1000";
$item_params->currency="RUB";
$item_params->total_price="495";
$package_params->item_params[] = $item_params;
$order_param->package_params = $package_params;
$req->setOrderParam(json_encode($order_param));
$resp = $c->execute($req, '50002600b29gjQbAozmuhedgVgivDyOFeFBSCnttl17d13abejHLp3DtxyozTuFgN7w');

echo json_encode($resp, JSON_UNESCAPED_SLASHES | JSON_UNESCAPED_UNICODE);
?>