name: Deploy to FTP

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Get list of changed files
      id: changed
      run: |
        git fetch origin master --depth=2
        git diff --name-only HEAD^ HEAD > changed_files.txt
    
    - name: Upload changed files via FTP
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        sudo apt-get update && sudo apt-get install -y lftp

        while IFS= read -r file; do
          if [[ -f "$file" ]]; then
            echo "Uploading $file..."
            lftp -u "$FTP_USERNAME","$FTP_PASSWORD" "$FTP_HOST" -e "set ftp:ssl-allow no; put -O /www/kids-universe.ru/ \"$file\"; bye"
          fi
        done < changed_files.txt