name: Deploy to FTP

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Get list of changed files
      id: changed
      run: |
        git fetch origin master --depth=2
        git diff --name-only HEAD^ HEAD > changed_files.txt
        echo "Changed files:" && cat changed_files.txt
    
    - name: Upload changed files via FTP
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        sudo apt-get update && sudo apt-get install -y lftp

        echo "Uploading the following files:"
        cat changed_files.txt

        while IFS= read -r file; do
          echo "Uploading $file..."
          dir=$(dirname "$file")
          lftp -d -u "$FTP_USERNAME","$FTP_PASSWORD" "$FTP_HOST" -e "set ftp:ssl-allow no; mkdir -p /www/kids-universe.ru/$dir; put -O /www/kids-universe.ru/$dir \"$file\"; bye"
        done < changed_files.txt