name: Deploy to FTP

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Get list of changed files
      id: changed
      run: |
        git fetch origin master --depth=2
        echo "CHANGED_FILES<<EOF" >> $GITHUB_ENV
        git diff --name-only HEAD^ HEAD >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    - name: Upload changed files via FTP
      env:
        FTP_HOST: ${{ secrets.FTP_HOST }}
        FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
        FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
      run: |
        sudo apt-get update && sudo apt-get install -y lftp

        while IFS= read -r file; do
          if [[ -f "$file" ]]; then
            echo "Uploading $file..."
            echo -e "open $FTP_HOST\nset ftp:ssl-allow no\nput -O /www/kids-universe.ru/ \"$file\"\nbye" > upload.cmd
            lftp -u "$FTP_USERNAME","$FTP_PASSWORD" -f upload.cmd
          fi
        done <<< "$CHANGED_FILES"