name: Deploy to FTP

on:
  push:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get list of changed files
        id: changed
        run: |
          git fetch origin master --depth=2
          git diff --name-only HEAD^ HEAD > changed_files.txt
          echo "Changed files:" && cat changed_files.txt

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          protocol: ftp
          local-dir: ./
          server-dir: /www/kids-universe.ru/
          dangerous-clean-slate: true
          exclude: |
            .git*
            .github*
            changed_files.txt