name: Deploy to FTP

on:
  push:
    branches:
      - master # Change this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install FTP client
      run: sudo apt-get install -y lftp

    - name: Upload to FTP
      run: |
        lftp -c "open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -R --only-newer -e . /www/kids-universe.ru"